### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by daniel-inacio** [rodenis/reader-plugin#1]
Hello how can I use the plugin ? Do you have any examples ?

**Comment by rodenis** [comment]
Hello, this project was for internal use only. I placed it on github to share with my colleagues.
So, I have no special examples. The only projet, that uses this plugin is here: https://github.com/rodenis/riocard-bonuser

**Comment by daniel-inacio** [comment]
Ok , thank you then.


2015-04-16 13:51 GMT-03:00 Denis Rodin <notifications@github.com>:

> Hello, this project was for internal use only. I placed it on github to
> share with my colleagues.
> So, I have no special examples. The only projet, that uses this plugin is
> here: https://github.com/rodenis/riocard-bonuser
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodenis/reader-plugin/issues/1#issuecomment-93783329>.
>



-- 
*_______________________________*

*Atenciosamente*,
*  Daniel Inácio*
 Desenvolvedor Web

 (16) 99280-7747 / 99777-7747
  daniel.inacio@orgsystem.com.br

**Comment by robertbaker** [comment]
@daniel-inacio Did you find a solution or figure it out? Need to use a magnetic card reader plugin too.

**Comment by rodenis** [comment]
The project is closed a year ago. It uses proprietary driver from vendor of our card-readers. So It isn't universal. It only fits one kind of protocol. We didn't know even the name of that protocol. Chineese vendor gave us that android driver with his devices.
